from power_bank.model.model_custom_errors.custom_errors import NotFoundExceptions
